# Generated by Django 2.0.3 on 2018-11-10 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('sex', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('sex', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=50)),
                ('release_date', models.DateField()),
                ('runtime', models.IntegerField()),
                ('ratings', models.FloatField()),
                ('cast', models.ManyToManyField(to='api.Actor')),
                ('directors', models.ManyToManyField(to='api.Director')),
                ('genres', models.ManyToManyField(to='api.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionCompany',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='TV',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('ratings', models.FloatField()),
                ('no_of_seasons', models.IntegerField()),
                ('no_of_episodes', models.IntegerField()),
                ('cast', models.ManyToManyField(to='api.Actor')),
                ('directors', models.ManyToManyField(to='api.Director')),
                ('genres', models.ManyToManyField(to='api.Genre')),
                ('production_companies', models.ManyToManyField(to='api.ProductionCompany')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('dob', models.DateField(default=datetime.date.today)),
                ('sex', models.CharField(max_length=1)),
                ('liked_movies', models.ManyToManyField(to='api.Movie')),
                ('liked_tv', models.ManyToManyField(to='api.TV')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='production_companies',
            field=models.ManyToManyField(to='api.ProductionCompany'),
        ),
    ]
