# Generated by Django 2.0.3 on 2018-11-09 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20181109_2337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='production_company',
            new_name='production_companies',
        ),
    ]
