# Generated by Django 2.0.3 on 2018-03-28 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180328_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favorites',
            field=models.CharField(blank=True, max_length=1000000000),
        ),
    ]
