# Generated by Django 2.0.3 on 2018-11-10 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_productioncompany_homepage_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='director',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='productioncompany',
            name='origin_country',
        ),
    ]
