# Generated by Django 2.0.3 on 2018-04-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180328_1318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='favorites',
            new_name='favorite_movies',
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_tv',
            field=models.CharField(blank=True, max_length=1000000000),
        ),
    ]
